FROM node:14.3

# Create app directory
WORKDIR /usr/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
# COPY .env ./
# COPY .npmrc ./

ARG tag=0 

ENV github_tag=${tag}

#RUN npm install -g yarn
#RUN yarn
RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

#po
EXPOSE 3000
CMD [ "npm","run","start" ]