# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - development
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: branch name
        run: echo "${{github.ref}}"
      - name: Checkout branch "${{github.ref}}"
        if: github.ref == 'refs/heads/development'
        uses: actions/checkout@v2
        with:
          ref: 'development'
        if: github.ref == 'refs/heads/master'
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: create a release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
           
      # - name: Get current date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"
      # - name: Checkout branch "master"
      #   uses: actions/checkout@v2
      #   with:
      #     ref: 'master'
      # - name: Release snapshot
      #   id: release-snapshot
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.date.outputs.date }}
      #     release_name: ${{ steps.date.outputs.date }}
      #     draft: false
      #     prerelease: false