# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - development
      - master
      - qa
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch "development"
        if: github.ref == 'refs/heads/development'
        uses: actions/checkout@v2
        with:
          ref: 'development'
      - name: Checkout branch "master"
        if: github.ref == 'refs/heads/master'
        uses: actions/checkout@v2
        with:
          ref: 'master'     
      - name: Checkout branch "QA"
        if: github.ref == 'refs/heads/qa'
        uses: actions/checkout@v2
        with:
          ref: 'qa' 
      - name: create a release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  getTag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          ref: 'master'
          fetch-depth: 0 # Required due to the weg Git
      - name: 'tag plugin'
        id: tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: tag
        run: echo ${{steps.tag.outputs.tag }}
      - name: 'job id'
        run: echo ${{github.run_id}}
      - name: 'commit id'
        run: echo ${{github.event.commits[0].id}}   
      - name: docker build
        run: |
          ls -la
          docker build . -t test-package -f dockerFile --build-arg github_tag=${{steps.tag.output.tag}}   
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"



      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: pathak4477
      #     password: P@ssw0rd4477

      # - name: Push to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: pathak4477/test-package:latest
      #     secrets: |
      #       "GITHUB_TAG=V10.2.4"




           
      # - name: Get current date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"
      # - name: Checkout branch "master"
      #   uses: actions/checkout@v2
      #   with:
      #     ref: 'master'
      # - name: Release snapshot
      #   id: release-snapshot
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.date.outputs.date }}
      #     release_name: ${{ steps.date.outputs.date }}
      #     draft: false
      #     prerelease: false
